# Generated by Django 3.0.6 on 2020-05-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='docs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
