# Generated by Django 3.0.6 on 2020-05-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0003_review_reviewupvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_modified',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='upvotes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
