# Generated by Django 3.0.6 on 2020-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0005_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_id', models.IntegerField()),
                ('credit', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
