# Generated by Django 3.0.6 on 2020-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereview', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploader_id',
            field=models.IntegerField(null=True),
        ),
    ]
